--INNER JOIN
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A INNER JOIN FROM_ITEM_B 
ON FROM_ITEM_A.STATE = FROM_ITEM_B.STATE;

WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A INNER JOIN FROM_ITEM_B 
ON FROM_ITEM_A.STATE != FROM_ITEM_B.STATE;

--CROSS JOIN
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A CROSS JOIN FROM_ITEM_B;

WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A, FROM_ITEM_B;

--OUTER JOIN
WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE
UNION ALL SELECT 'A CORUNA' AS CITY, 'GALICIA' AS STATE
UNION ALL SELECT 'SÃO PAULO' AS CITY, 'SÃO PAULO' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY
UNION ALL SELECT 'RIO DE JANEIRO' AS STATE, 'BRASIL' AS COUNTRY
UNION ALL SELECT 'MEXICO CITY' AS STATE, 'MEXICO' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A INNER JOIN FROM_ITEM_B
ON FROM_ITEM_A.STATE = FROM_ITEM_B.STATE;

WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE
UNION ALL SELECT 'A CORUNA' AS CITY, 'GALICIA' AS STATE
UNION ALL SELECT 'SÃO PAULO' AS CITY, 'SÃO PAULO' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY
UNION ALL SELECT 'RIO DE JANEIRO' AS STATE, 'BRASIL' AS COUNTRY
UNION ALL SELECT 'MEXICO CITY' AS STATE, 'MEXICO' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A FULL OUTER JOIN FROM_ITEM_B
ON FROM_ITEM_A.STATE = FROM_ITEM_B.STATE;

WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE
UNION ALL SELECT 'A CORUNA' AS CITY, 'GALICIA' AS STATE
UNION ALL SELECT 'SÃO PAULO' AS CITY, 'SÃO PAULO' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY
UNION ALL SELECT 'RIO DE JANEIRO' AS STATE, 'BRASIL' AS COUNTRY
UNION ALL SELECT 'MEXICO CITY' AS STATE, 'MEXICO' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A LEFT JOIN FROM_ITEM_B
ON FROM_ITEM_A.STATE = FROM_ITEM_B.STATE;

WITH FROM_ITEM_A AS
(SELECT 'DALLAS' AS CITY, 'OR' AS STATE
UNION ALL SELECT  'TOKYO' AS CITY, 'TOKYO' AS STATE
UNION ALL SELECT 'MUMBAI' AS CITY, 'MAHARASHIRA' AS STATE
UNION ALL SELECT 'A CORUNA' AS CITY, 'GALICIA' AS STATE
UNION ALL SELECT 'SÃO PAULO' AS CITY, 'SÃO PAULO' AS STATE),
FROM_ITEM_B AS (
    SELECT 'OR' AS STATE, 'USA' AS COUNTRY
UNION ALL SELECT 'TOKYO' AS STATE, 'JAPAN' AS COUNTRY
UNION ALL SELECT 'MAHARASHIRA' AS STATE, 'INDIA' AS COUNTRY
UNION ALL SELECT 'RIO DE JANEIRO' AS STATE, 'BRASIL' AS COUNTRY
UNION ALL SELECT 'MEXICO CITY' AS STATE, 'MEXICO' AS COUNTRY)
SELECT FROM_ITEM_A.*, COUNTRY 
FROM FROM_ITEM_A RIGHT JOIN FROM_ITEM_B
ON FROM_ITEM_A.STATE = FROM_ITEM_B.STATE;

--`bigquery-public-data`.new_york_citibike.citibike_trips
--`bigquery-public-data.ghcn_d.ghcnd_2016`

WITH bicycle_rentals AS (
SELECT COUNT(starttime) AS num_trips,
EXTRACT(DATE FROM starttime) AS trip_date
FROM `bigquery-public-data`.new_york_citibike.citibike_trips
GROUP BY trip_date),

rainy_days AS (
SELECT date, (MAX(precip) > 5) AS rainy FROM
(SELECT date, IF(element = 'PRCP', value/10, NULL) AS precip
FROM `bigquery-public-data.ghcn_d.ghcnd_2016`
WHERE id = 'USW00094728')
GROUP BY date)

SELECT bicycle_rentals.trip_date,
bicycle_rentals.num_trips,
rainy_days.rainy 
FROM bicycle_rentals 
INNER JOIN rainy_days 
ON bicycle_rentals.trip_date = rainy_days.date
WHERE rainy_days.rainy = TRUE
ORDER BY trip_date;

--
WITH bicycle_rentals AS (
SELECT COUNT(starttime) AS num_trips,
EXTRACT(DATE FROM starttime) AS trip_date
FROM `bigquery-public-data`.new_york_citibike.citibike_trips
GROUP BY trip_date),

rainy_days AS (
SELECT date, (MAX(precip) > 5) AS rainy FROM
(SELECT date, IF(element = 'PRCP', value/10, NULL) AS precip
FROM `bigquery-public-data.ghcn_d.ghcnd_2016`
WHERE id = 'USW00094728')
GROUP BY date)

SELECT AVG(bicycle_rentals.num_trips) AS num_trips_AVG,
rainy_days.rainy 
FROM bicycle_rentals 
INNER JOIN rainy_days 
ON bicycle_rentals.trip_date = rainy_days.date
GROUP BY rainy_days.rainy;

